#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
INFRA_DIR="$ROOT_DIR/infra"
FRONTEND_DIR="$ROOT_DIR/apps/frontend"
OUTPUT_JSON="$INFRA_DIR/outputs.json"
ENV_FILE="$FRONTEND_DIR/.env.production"

# shellcheck source=./lib/common.sh
source "$SCRIPT_DIR/lib/common.sh"

load_env_defaults "$ROOT_DIR/.env"

ENV="${DEPLOY_ENV:-dev}"
AWS_REGION="${AWS_DEFAULT_REGION:-eu-west-1}"
FRONTEND_TARGET="${FRONTEND_DEPLOY_TARGET:-$(frontend_target_for_env "$ENV")}"
PAGES_BASE_PATH="$(normalize_base_path "${PAGES_BASE_PATH:-/awdah/}")"
FRONTEND_API_MODE="${FRONTEND_API_MODE:-}"

if [ -z "$FRONTEND_API_MODE" ]; then
  if [ "$FRONTEND_TARGET" = "pages" ]; then
    FRONTEND_API_MODE="direct"
  else
    FRONTEND_API_MODE="same-origin"
  fi
fi

FRONTEND_BASE_PATH="/"
if [ "$FRONTEND_TARGET" = "pages" ]; then
  FRONTEND_BASE_PATH="$PAGES_BASE_PATH"
fi

echo "=> Generating frontend configuration for environment: $ENV"

if [ ! -f "$OUTPUT_JSON" ]; then
  echo "=> [Error] outputs.json not found. Please run a deployment first."
  exit 1
fi

# Use Node.js for reliable JSON parsing and merge-aware .env generation
node <<EOF
const fs = require('fs');
const path = require('path');

const outputsPath = '$OUTPUT_JSON';
const envPath = '$ENV_FILE';
const env = '$ENV';
const region = '$AWS_REGION';
const frontendTarget = '$FRONTEND_TARGET';
const frontendApiMode = '$FRONTEND_API_MODE';
const frontendBasePath = '$FRONTEND_BASE_PATH';

/** Parses a .env file into a simple key-value object. */
function parseEnv(filePath) {
  if (!fs.existsSync(filePath)) return {};
  const content = fs.readFileSync(filePath, 'utf8');
  const result = {};
  content.split('\n').forEach(line => {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('#')) return;
    const [key, ...valueParts] = trimmed.split('=');
    if (key) result[key] = valueParts.join('=');
  });
  return result;
}

/** Writes a key-value object to a .env file. */
function writeEnv(filePath, config) {
  const content = [
    '# Generated by scripts/generate-frontend-config.sh',
    ...Object.entries(config).map(([key, value]) => \`\${key}=\${value}\`)
  ].join('\n') + '\n';
  fs.writeFileSync(filePath, content);
}

try {
  const outputs = JSON.parse(fs.readFileSync(outputsPath, 'utf8'));
  const currentEnv = parseEnv(envPath);
  
  // Find stacks by env name
  const apiStack = outputs[\`Awdah-api-stack-\${env}\`];
  const authStack = outputs[\`Awdah-auth-stack-\${env}\`];
  
  const newConfig = { ...currentEnv };
  newConfig['VITE_BASE_PATH'] = frontendBasePath;

  // Only update if the stack outputs were actually part of this deployment
  if (apiStack && apiStack.ApiUrl) {
    if (frontendApiMode === 'direct') {
      newConfig['VITE_API_BASE_URL'] = apiStack.ApiUrl;
    } else {
      // Prefer same-origin in cloud deploys for stability; CloudFront proxies `/v1/*`.
      newConfig['VITE_API_BASE_URL'] = '';
    }
  }
  
  if (authStack) {
    if (authStack.UserPoolId) newConfig['VITE_COGNITO_USER_POOL_ID'] = authStack.UserPoolId;
    if (authStack.UserPoolClientId) newConfig['VITE_COGNITO_CLIENT_ID'] = authStack.UserPoolClientId;
  }

  // Always keep these updated as they are regional/stable
  newConfig['VITE_AWS_REGION'] = region;
  if (!newConfig['VITE_AUTH_MODE']) newConfig['VITE_AUTH_MODE'] = 'cognito';

  writeEnv(envPath, newConfig);
  
  console.log(\`=> Frontend configuration updated (merge-aware) at: \${envPath}\`);
  console.log(\`   - Target host: \${frontendTarget}\`);
  console.log(\`   - Base path: \${frontendBasePath}\`);
  if (apiStack && apiStack.ApiUrl) {
    const printed = frontendApiMode === 'direct' ? apiStack.ApiUrl : '<same-origin /v1>';
    console.log(\`   - Updated API URL: \${printed}\`);
  }
  if (authStack && authStack.UserPoolId) console.log(\`   - Updated User Pool: \${authStack.UserPoolId}\`);
} catch (err) {
  console.error('=> [Error] Failed to generate frontend configuration:', err.message);
  process.exit(1);
}
EOF
