#!/bin/bash
set -e

# setup-hybrid-dev.sh
# Points the local frontend to the AWS dev backend.
# Usage: ./scripts/setup-hybrid-dev.sh [env]

ENV=${1:-dev}
REGION=${AWS_DEFAULT_REGION:-eu-west-1}

echo "🚀 Setting up Hybrid Dev for environment: $ENV"

# 1. Deploy backend (api + auth + data)
echo "📦 Ensuring backend is deployed..."
cd infra
npx cdk deploy Awdah-auth-stack-$ENV Awdah-api-stack-$ENV Awdah-data-stack-$ENV --context env=$ENV --require-approval never
cd ..

# 2. Extract Outputs
echo "📋 Fetching outputs from CloudFormation..."

get_output() {
    local STACK=$1
    local KEY=$2
    aws cloudformation describe-stacks \
        --stack-name "$STACK" \
        --region "$REGION" \
        --query "Stacks[0].Outputs[?OutputKey=='$KEY'].OutputValue" \
        --output text
}

API_URL=$(get_output "Awdah-api-stack-$ENV" "ApiUrl")
USER_POOL_ID=$(get_output "Awdah-auth-stack-$ENV" "UserPoolId")
CLIENT_ID=$(get_output "Awdah-auth-stack-$ENV" "UserPoolClientId")

if [ -z "$API_URL" ] || [ -z "$USER_POOL_ID" ]; then
    echo "❌ Error: Could not find stack outputs. Ensure stacks are deployed first."
    exit 1
fi

# 3. Create .env.local
echo "📝 Writing to apps/frontend/.env.local..."
cat <<EOF > apps/frontend/.env.local
# This file is auto-generated by scripts/setup-hybrid-dev.sh
VITE_AUTH_MODE=cognito
VITE_API_BASE_URL=$API_URL
VITE_AWS_REGION=$REGION
VITE_COGNITO_USER_POOL_ID=$USER_POOL_ID
VITE_COGNITO_CLIENT_ID=$CLIENT_ID
EOF

echo -e "\n✅ \033[0;32mHybrid Dev Ready!\033[0m"
echo -e "💡 Run \033[1;33mnpm run dev\033[0m to start the app using the AWS backend."
echo -e "💡 To switch back to local mode, run \033[1;33mnpm run dev:local\033[0m."
