#!/bin/sh

if [ "${CI:-}" = "true" ] || [ "${GITHUB_ACTIONS:-}" = "true" ]; then
	exit 0
fi

if [ "${RUN_FULL_PRE_PUSH:-0}" = "1" ]; then
	RUN_E2E=1 ./scripts/pre-push-checks.sh
else
	./scripts/pre-push-quick.sh
fi
